// <auto-generated />
using System;
using AudioGearTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioGearTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130070558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioGearTracker.Core.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "France",
                            Name = "Focal"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Japan",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            Name = "Benchmark"
                        });
                });

            modelBuilder.Entity("AudioGearTracker.Core.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ReviewScore")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ModelName = "Utopia",
                            Notes = "大烏，主力耳機",
                            Price = 130000m,
                            ReviewScore = 9.8000000000000007,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            ModelName = "Clear MG",
                            Notes = "偏暖厚、密度高",
                            Price = 45000m,
                            ReviewScore = 9.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            ModelName = "IER-M9",
                            Notes = "監聽入耳式",
                            Price = 28000m,
                            ReviewScore = 8.5,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            ModelName = "DAC3 HGC",
                            Notes = "借用中",
                            Price = 60000m,
                            PurchaseDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewScore = 8.8000000000000007,
                            Type = 1
                        });
                });

            modelBuilder.Entity("AudioGearTracker.Core.Entities.Equipment", b =>
                {
                    b.HasOne("AudioGearTracker.Core.Entities.Brand", "Brand")
                        .WithMany("Equipments")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("AudioGearTracker.Core.Entities.Brand", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
